Complete Rewrite
Added:
Better error handling, much more verbosity during execution,
installation of f2fs-tools into the target and support for automatic
F2FS expansion
with an image target.

Changed:
We now create an entirely new partition from scratch, instead of
copying the existing partition table.
Fully disabled the ext4 expansion script.

Many more small changes.

diff --git a/raspbian-f2fs b/raspbian-f2fs
--- a/raspbian-f2fs
+++ b/raspbian-f2fs
@@ -1,151 +1,409 @@
-#!/bin/sh
+#!/bin/bash
 
-loopold=/dev/loop5
-newdev=/dev/loop6
-mntold=./old
-mntnew=./new
+# Raspbian-F2FS v207
+# Original Script: https://github.com/d-a-v/raspbian-f2fs
+# Complete re-write by Timothy Brown - August 2018.
+#
+# This script operates in two modes:
+# 1. Device Target Mode: In this mode the script will format an SD card or
+# USB flash drive as F2FS (Flash Friendly Filesystem) and copy a fully bootable
+# installation of Raspbian onto it.
+#
+# 2. Image Target Mode: This mode takes a fresh image of Raspbian and converts
+# the root partition from EXT4 to F2FS. The resulting image can be written to an
+# SD card or USB flash device just like the original image. These images will
+# automatically expand to fit the media on first boot.
+#
+# Both modes require an untouched zip or img file of Raspbian or Raspbian Lite,
+# which can be downloaded from www.raspberrypi.org.
+#
+# This script has only been tested *running on* Raspbian Stretch, other distros
+# *may* work if the proper packages are installed (f2fs-tools, pv) or tweaks to
+# the script are made.
+#
+# Syntax: raspbian-f2fs source.zip|img /dev/target|target.img
 
-u()
-{
-echo "-------- UNMOUNT EVERYTHING"
-sudo umount $mntold || true
-sudo umount $mntnew || true
-sudo umount $loopold || true
-sudo umount $newdev || true
-sudo losetup -d $loopold || true
-$file && sudo losetup -d $newdev || true
-echo "-------- UNMOUNT DONE"
-}
+cmdname="$(basename $0)"
+filename="$1"
+targetdev=""
+targetboot=/mnt/target_boot
+targetroot=/mnt/target_root
+sourcedev=$(losetup -f)
+sourceboot=/mnt/source_boot
+sourceroot=/mnt/source_root
+
+imgsrc="${filename%%.*}.img"
+
+raspimgver="2018-06-27"
+scriptver="v207"
 
 set -e
 
-if [ -z "$1" ]; then 
-	echo "syntax: raspian-image.zip [/dev/sdcarddev]"
+# Print header.
+echo "                                                                               "
+echo "Raspbian F2FS SD/Flash Drive Creation Tool $scriptver"
+echo "-------------------------------------------------------------------------------"
+echo "                                                                               "
+
+# Make sure both command line arguments are provided.
+if [ -z "$1" ] || [ -z "$2" ]; then
+	echo "Syntax: $cmdname source.zip|img /dev/target|target.img"
+	echo "[Source] A zip file or image of Raspbian."
+	echo "[Target] The device to flash or new image file to create."
+	echo "                                                                               "
+	echo "Example: $cmdname /mnt/usb/2018-06-27-raspbian.img /dev/sdb"
+	echo "This will generate a bootable F2FS version of Raspbian from an image file"
+	echo "and flash it onto an externally attached SD card."
 	exit 1
 fi
 
-zip="$1"
-imgsrc="${zip}.img"
-imgf2fs="${zip}.f2fs-img"
+# Make sure we're running as root.
+if [ ! "$(whoami)" = "root" ]; then
+	echo "Error: This script *must* be run as root!"
+	echo "       Please use 'sudo su -' and then re-run this script."
+	exit 1
+fi
 
-dev="$2"
-file=true
-if [ ! -z "$dev" ]; then
-	(echo p; echo q) | sudo fdisk "$dev"
-	echo "---- THIS WILL BE WIPED - are you sure (yes) ?"
+# Verify script compatibility.
+echo "${cmdname}: Verifying source image compatibility."
+case "$(basename ${filename%%.*})" in
+	*${raspimgver}*)
+	echo "Source Image = $(basename ${filename%%.*})"
+	;;
+	*)
+	echo "******************* WARNING *******************"
+	echo "Source Image: $(basename ${filename%%.*})"
+	echo "This version of Raspbian has not been tested   "
+	echo "with this script. Proceede at your own risk.   "
+	echo "This is not a joke. Must bring your own weapons."
+	echo "************ SAFETY NOT GUARANTEED ************"
+	echo "                                               "
+	sleep 5
+	;;
+esac
+
+# Make sure required software is installed.
+if [ "$(dpkg-query -W -f='${Status}' pv 2>/dev/null | grep -c "ok installed")" == "0" ]; then
+	echo "${cmdname}: Installing required package [pv]."
+	apt-get -qq install pv
+fi
+if [ "$(dpkg-query -W -f='${Status}' f2fs-tools 2>/dev/null | grep -c "ok installed")" == "0" ]; then
+	echo "${cmdname}: Installing required package [f2fs-tools]."
+	apt-get -qq install f2fs-tools
+fi
+
+# Do not unzip if we're already working with an image.
+if [ "${filename#*.}" = "zip" ]; then
+	echo "${cmdname}: Unzipping $filename -> $imgsrc."
+	test -r "$imgsrc" || unzip -p "$filename" > "$imgsrc"
+fi
+
+# Check to see if our target is a device or image.
+echo "${cmdname}: Verifying target."
+if [ -b "$2" ]; then
+	targetdev="$2"
+	targetimg=""
+	case "$targetdev" in
+		"/dev/mmcblk"*)
+		echo "[Block Device] Internal SD Card"
+		target_p1="p1"
+		target_p2="p2"
+		;;
+		"/dev/sd"*)
+		echo "[Block Device] External USB Flash/SD Card"
+		target_p1="1"
+		target_p2="2"
+		;;
+	esac
+	echo "********** THIS DEVICE WILL BE WIPED **********"
+	parted -s "$targetdev" print || true
+	echo "**********    Are you sure? (yes)    **********"
 	read ans
 	test $ans = "yes" || exit 1
-	file=false
-fi
-
-echo "unzipping"
-# do not unzip if already done
-test -r "$imgsrc" || unzip -p "$zip" > "$imgsrc"
-# copy image if creating new one
-$file && { test -r "$imgf2fs" || cp "$imgsrc" "$imgf2fs"; }
-
-# partition offsets in images
-offset1=$(($(echo p | fdisk "$imgsrc" | grep "${imgsrc}1" | awk '{print $2;}') * 512))
-sect2=$(echo p | fdisk "$imgsrc" | grep "${imgsrc}2" | awk '{print $2;}')
-offset2=$(($sect2 * 512))
-
-u # unmount all
-mkdir -p $mntold
-mkdir -p $mntnew
-
-#######################################
-#### update partition table
-
-if ! $file; then
-	echo "copy partition table"
-	# copy partition tables from old image to $dev
-	sudo dd if=$imgsrc of=$dev bs=512 count=1
-	echo "copy partition table: done"
-	echo "resize partition 2"
-	sudo partprobe $dev
-	# on sdcard, resize partition2 to max
-	cat << EOF | sudo fdisk ${dev}
-p
-d
-2
-n
-p
-2
-$sect2
-
-
-w
-p
-q
-EOF
-	echo "partition 2 resized"
-	sudo partprobe $dev
-	newdev=${dev}2
-fi
-
-#######################################
-#### now dealing with partition 1
-
-if $file; then
-	# mount new partition
-	sudo losetup -o $offset1 $newdev "$imgf2fs"
-	sudo mount $newdev $mntnew
+elif [ ! -e "$2" ]; then
+	echo "[Loop Device] Internal Disk Image"
+	targetdev=""
+	targetimg="$2"
+	target_p1="p1"
+	target_p2="p2"
 else
-	# mount old prtition to copy onto sdcard
-	sudo losetup -o $offset1 $loopold "$imgsrc"
-	sudo mount -o ro $loopold $mntold
-	# format sdcard part1
-	sudo mkdosfs ${dev}1
-	# mount sdcard
-	sudo mount ${dev}1 $mntnew
-	# copy
-	echo "rsyncing boot"
-	sudo rsync -a $mntold/ $mntnew/
-	echo "rsync done"
+	echo "Target ($2) does not appear to be a valid device or the disk image already exists."
+	echo "Aborting."
+	exit 1
 fi
 
-echo "patching boot"
-[ -f $mntnew/cmdline.txt.old ] || sudo mv $mntnew/cmdline.txt $mntnew/cmdline.txt.old
-sed -e 's/rootfstype=[^ ]*/rootfstype=f2fs/g' < $mntnew/cmdline.txt.old | sudo dd of=$mntnew/cmdline.txt
+# Verify nothing is currently mounted.
+echo "${cmdname}: Making sure source and target aren't mounted."
+if [ -b "$sourcedev" ]; then
+	umount ${sourcedev}* 2> /dev/null || true
+fi
+if [ -b "$targetdev" ]; then
+	umount ${targetdev}* 2> /dev/null || true
+fi
+losetup -d $(losetup -O NAME -n -j "$imgsrc") 2> /dev/null || true
+losetup -d $(losetup -O NAME -n -j "$targetimg") 2> /dev/null || true
 
-echo "press enter before unmounting partition 1"
-read junk
-u
+# Setup source and target mount points.
+echo "${cmdname}: Setting up mount points."
+test -r /mnt || mkdir -p /mnt
+test -r "$sourceboot" || mkdir -p "$sourceboot"
+test -r "$sourceroot" || mkdir -p "$sourceroot"
+test -r "$targetboot" || mkdir -p "$targetboot"
+test -r "$targetroot" || mkdir -p "$targetroot"
+
+# If our target is an image, create it now.
+if [ ! -z "$targetimg" ]; then
+	echo "${cmdname}: Creating blank disk image."
+	let targetimgsize=$(du --block-size=M $imgsrc | cut -d "M" -f1)+200
+	truncate -s ${targetimgsize}M "$targetimg"
+	echo "${cmdname}: Attaching target disk image."
+	targetdev=$(losetup --show -f -P "$targetimg")
+fi
+
+# Mount source image.
+echo "${cmdname}: Attaching source disk image."
+sourcedev=$(losetup --show -f -P "$imgsrc")
+echo "${cmdname}: Mounting source boot partition."
+mount -o ro ${sourcedev}p1 $sourceboot
+echo "${cmdname}: Mounting source root partition."
+mount -o ro ${sourcedev}p2 $sourceroot
 
 #######################################
-#### now dealing with partition 2
+# Write out partition table.
 
-$file || newdev=${dev}2
+# Wipe exsisting partition data from target.
+echo "${cmdname}: Erasing current partition table on target."
+wipefs -aq $targetdev
+# Generate new MBR style partition table and two partitions:
+# P1 = 64MiB FAT32 LBA with 8192 sector offset.
+# P2 = Remaining Space Linux filesystem directly after the first partition.
+echo "${cmdname}: Creating new partition table on target."
+parted -s $targetdev mklabel msdos mkpart primary fat32 8192s 64MiB mkpart primary ext2 64MiB 100%
+# Reload the partition table.
+partprobe $targetdev
+# Print the new partition table.
+parted -s $targetdev print
+# Read the new partition UUIDs.
+bootuuid=$(blkid -o value -s PARTUUID ${targetdev}$target_p1)
+rootuuid=$(blkid -o value -s PARTUUID ${targetdev}$target_p2)
 
-# setup loop devices on images'part2
-sudo losetup -o $offset2 $loopold "$imgsrc"
-$file && sudo losetup -o $offset2 $newdev "$imgf2fs"
+#######################################
+# Now dealing with partition 1.
 
-# mount old image part2
-sudo mount -o ro "$loopold" $mntold
+# Format target partition 1 as FAT32.
+echo "${cmdname}: Formatting boot partition on target as FAT32."
+mkfs.fat -n boot ${targetdev}$target_p1
+# Mount target parition 1.
+echo "${cmdname}: Mounting target boot partition."
+mount ${targetdev}$target_p1 $targetboot
+# Count files.
+echo "${cmdname}: Getting file count on source."
+numfiles=$(find $sourceboot/ -type f -printf . | wc -c)
+# Copy boot files from source to target.
+echo "${cmdname}: Copying $numfiles files from source image to target device."
+rsync -axi $sourceboot/ $targetboot/ | pv -leps $numfiles >/dev/null
+# Update cmdline.txt on the target.
+echo "${cmdname}: Updating cmdline.txt options."
+cp $targetboot/cmdline.txt $targetboot/cmdline.old
+sed -i 's/rootfstype=[^ ]*/rootfstype=f2fs/g' $targetboot/cmdline.txt
+sed -i 's/root=[^ ]*/root=PARTUUID='"$rootuuid"'/g' $targetboot/cmdline.txt
+## If target is a device then stop the partition resize script from running on boot.
+if [ -z "$targetimg" ]; then
+	sed -i 's| init=/usr/lib/raspi-config/init_resize.sh||' $targetboot/cmdline.txt
+	if ! grep -q splash "$targetboot/cmdline.txt"; then
+		sed -i 's/ quiet//g' $targetboot/cmdline.txt
+	fi
+fi
 
-# create f2fs partition (sdcar or new image) part2
-sudo mkfs.f2fs $newdev
-# mount it
-sudo mount $newdev $mntnew
-# copy
-echo "rsync - may take time"
-sudo rsync -a $mntold/ $mntnew/
-echo "rsync done"
-# update fstab
-sudo mv $mntnew/etc/fstab $mntnew/etc/fstab.old
-sed -e 's/ext4.*/f2fs\tdefaults,noatime,discard\t0 1/g' < $mntnew/etc/fstab.old | sudo dd of=$mntnew/etc/fstab
-# remove resize2fs script
-sudo rm -f $mntnew/etc/*/*resize2fs_once
-# remove swap file default creation
-sudo rm -f $mntnew/etc/rc*/*dphys-swapfile
-
-echo "done with part2"
-echo "you can check parition2 in new/"
-echo "syncing... (will take several minute on sdcard)"
+# Sync
+echo "${cmdname}: Done processing the boot partition!"
+echo "${cmdname}: Syncing..."
 sync
-echo "press enter before unmounting part2"
-read junk
-u
 
+#######################################
+# Now dealing with partition 2.
+
+# Format target parition 2 as F2FS.
+echo "${cmdname}: Formatting root partition on target as F2FS."
+mkfs.f2fs -l root ${targetdev}$target_p2
+# Mount target partition 2.
+echo "${cmdname}: Mounting target root partition."
+mount ${targetdev}$target_p2 $targetroot
+# Count files.
+echo "${cmdname}: Getting file count on source image."
+numfiles=$(df -i $sourceroot/ | perl -ane 'print $F[2] if $F[5] =~ m:^/:')
+# Copy root files from source to target.
+echo "${cmdname}: Copying $numfiles files from source image to target device."
+rsync -axi $sourceroot/ $targetroot/ | pv -leps $numfiles >/dev/null
+# Update fstab on the target.
+echo "${cmdname}: Generating new fstab on target."
+mv $targetroot/etc/fstab $targetroot/etc/fstab.old
+cat > $targetroot/etc/fstab << EOF
+proc                  /proc   proc    defaults                    0   0
+PARTUUID=$bootuuid  /boot   vfat    defaults                    0   2
+PARTUUID=$rootuuid  /       f2fs    defaults,noatime,discard    0   1
+EOF
+
+# If the target is an image, create scripts to resize the filesystem at boot.
+if [ ! -z "$targetimg" ]; then
+	echo "${cmdname}: Setting up F2FS filesystem expansion."
+	# Initramfs: F2FS Resize Hook Script
+	cat > "${targetroot}/etc/initramfs-tools/hooks/f2fsresize" << EOF
+#!/bin/sh
+# F2FS Resize Hook Script
+
+
+PREREQ=""
+prereqs()
+{
+	echo "\$PREREQ"
+}
+
+
+case \$1 in
+prereqs)
+	prereqs
+	exit 0
+	;;
+esac
+
+
+. /usr/share/initramfs-tools/hook-functions
+# Begin real processing below this line
+if [ ! -x "/sbin/resize.f2fs" ]; then
+	exit 0
+fi
+
+
+copy_exec /sbin/resize.f2fs
+exit 0
+EOF
+	chmod +x "${targetroot}/etc/initramfs-tools/hooks/f2fsresize"
+
+	# Initramfs: F2FS Resize Boot Script
+	cat > "${targetroot}/etc/initramfs-tools/scripts/init-premount/f2fsresize" << EOF
+#!/bin/sh
+# F2FS Resize
+
+PREREQ=""
+prereqs()
+{
+	echo "\$PREREQ"
+}
+
+case \$1 in
+prereqs)
+	prereqs
+	exit 0
+	;;
+esac
+
+. /scripts/functions
+# Begin real processing below this line
+if [ ! -x "/sbin/resize.f2fs" ]; then
+	panic "Resize.F2FS Executable Not Found"
+fi
+
+log_begin_msg "Expanding F2FS Filesystem"
+/sbin/resize.f2fs "/dev/disk/by-partuuid/$rootuuid" || panic "F2FS Resize Failed"
+log_end_msg
+
+exit 0
+EOF
+	chmod +x "${targetroot}/etc/initramfs-tools/scripts/init-premount/f2fsresize"
+
+	# Cleanup Script
+	cat > "${targetroot}/etc/f2fsresize_cleanup" << EOF
+#!/bin/bash
+printf "Successfully expanded F2FS volume!"
+sed -i '/\/bin\/bash \/etc\/f2fsresize_cleanup/d' /etc/rc.local
+sed -i '/initramfs initrd.img followkernel/d' /boot/config.txt
+mv /usr/lib/raspi-config/init_resize.old /usr/lib/raspi-config/init_resize.sh
+rm /boot/initrd.img
+rm /etc/initramfs-tools/scripts/init-premount/f2fsresize
+rm /etc/initramfs-tools/hooks/f2fsresize
+rm /etc/f2fsresize_cleanup
+EOF
+	chmod +x "${targetroot}/etc/f2fsresize_cleanup"
+
+	# Get kernel version.
+	kernelver=$(ls ${targetroot}/lib/modules/ | grep "v7+" | head -n 1)
+
+	# Modify the init_resize script to start our custom initramfs after expanding the partition.
+	test -r $targetroot/usr/lib/raspi-config/init_resize.sh || cp $targetroot/usr/lib/raspi-config/init_resize.sh $targetroot/usr/lib/raspi-config/init_resize.old
+	let linenum=$(grep -n "mount / -o remount,rw"  "$targetroot/usr/lib/raspi-config/init_resize.sh" | head -n 1 | cut -d: -f1)+2
+	sed -i ''"$linenum"'i echo "initramfs initrd.img followkernel" >> /boot/config.txt' "$targetroot/usr/lib/raspi-config/init_resize.sh"
+	sed -i ''"$linenum"'i sed -i \x27\x27"$(grep -n "exit 0"  "/etc/rc.local" | tail -n 1 | cut -d: -f1)"\x27i /bin/bash /etc/f2fsresize_cleanup\x27 /etc/rc.local' "$targetroot/usr/lib/raspi-config/init_resize.sh"
+fi
+
+echo "${cmdname}: Syncing..."
+sync
+
+#######################################
+# Now chrooting into the target rootfs.
+
+# Bind some host filesystems to target for chroot.
+echo "${cmdname}: Building up chroot enviroment on target rootfs."
+for i in dev proc sys dev/pts; do
+	mount --bind /$i $targetroot/$i
+done
+mount --bind $targetboot $targetroot/boot
+
+# Chroot into target and perform the following actions:
+# 1) Disable resize2fs_once script.
+# 2) Install f2fs-tools.
+# If the target is an image, additionally perform these actions:
+# 3) Generate initramfs for F2FS filesystem expansion.
+cat << EOF | chroot $targetroot env -i \
+LANG=en_GB.utf8 LANGUAGE=en_GB.utf8 LC_ALL=en_GB.utf8 TERM=$TERM HOME=/root /bin/bash --login
+echo "${cmdname}@${targetroot}: Stopping automatic ext4 filesystem expansion."
+update-rc.d resize2fs_once remove
+test -r /etc/init.d/resize2fs_once && rm /etc/init.d/resize2fs_once
+echo "${cmdname}@${targetroot}: Installing f2fs-tools."
+apt-get -qq install f2fs-tools
+apt-get -qq clean
+test -z "$targetimg" || echo "${cmdname}@${targetroot}: Generating initramfs for F2FS filesystem expansion."
+test -z "$targetimg" || mkinitramfs -o /boot/initrd.img $kernelver
+exit 0
+EOF
+
+# Unbind host filesystems from target.
+echo "${cmdname}: Tearing down chroot enviroment."
+sync
+sleep 1
+for i in boot dev/pts sys proc dev; do
+	umount $targetroot/$i
+done
+
+# Sync.
+echo "${cmdname}: Done processing the root partition!"
+echo "${cmdname}: Syncing..."
+sync
+
+# Print info on the new device.
+echo "${cmdname}: Successfully completed Raspbian F2FS installation!"
+echo "************************************************************"
+df -hT --total ${targetdev}$target_p1 ${targetdev}$target_p2
+echo "************************************************************"
+
+echo "${cmdname}: Unmounting everything."
+umount $sourceboot 2> /dev/null || true
+umount $sourceroot 2> /dev/null || true
+umount $targetboot 2> /dev/null || true
+umount $targetroot 2> /dev/null || true
+umount ${sourcedev}* 2> /dev/null || true
+umount ${targetdev}* 2> /dev/null || true
+losetup -d $sourcedev 2> /dev/null || true
+losetup -d $targetdev 2> /dev/null || true
+
+# Cleanup.
+echo "${cmdname}: Cleaning up."
+test -r "$sourceboot" && rm -rf $sourceboot
+test -r "$sourceroot" && rm -rf $sourceroot
+test -r "$targetboot" && rm -rf $targetboot
+test -r "$targetroot" && rm -rf $targetroot
+
+# Print footer.
+echo "                                                                               "
+echo "-------------------------------------------------------------------------------"
 #######################################
